package.json
scripts/autocomplete.cjs

Reverts affinidi/affinidi-cli#14

Revert "fix:  add prompt for auto completion [FTL-7958]"

---

src/commands/create/project.ts
src/commands/create/schema.ts
src/commands/login/index.ts

fix: remove redundant "affinidi" from command example

---

.eslintrc.js
package-lock.json
package.json
src/services/config/index.ts
src/services/user-management/index.ts
test/commands/logout/index.test.ts

Fixes the linting problem with mocha
[FTL-8187]
[FTL-8187]: https://lemmatree.atlassian.net/browse/FTL-8187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: test the store after signout

---

README.md

The ReadMe file has been written with the aim to help onboard a developer who is not familiar with Affinidi technology.   
It now follows this structure:
* Introduction (background and context)
* Features
* Installation
* Quick Start (Authentication, Projects, Schemas, VCs)
* CLI Commands (in alphabetical order)
* About Schemas and Verifiable Credentials (guidance on how to structure JSON source files for schema creation and vc issuance)
* FAQ (based on the Extension's [ReadMe](https://github.com/affinidi/vscode-extension) with minimal variations)
Once this is approved, we need to update the `--help` of each command and the `affinidi help` command itself

feat: [FTL-8172] Improved ReadMe file

---

README.md

Only here for investigating the semantic-release with personal access token

chore: min readme change

---

package-lock.json

<details><summary>Click to show screenshots</summary>
</details>

fix: vulnerability

---

README.md
src/commands/generate/app.ts
src/commands/iam/add-principal.ts
src/commands/iam/get-policies.ts
src/commands/iam/remove-principal.ts
src/commands/iam/update-policies.ts
src/commands/login/create-config.ts
src/commands/project/select-project.ts
src/commands/start.ts
src/commands/stop.ts
src/common/base-command.ts
src/helpers/generate-error-message.ts
src/helpers/prompt-required-flags.ts

feat: add no-input global flag

---

README.md
src/services/affinidi/errors/index.ts

Improvements to README file:
- Reorganized file
- Removed PAT and Policy details sections and instead linked to the documentation site
- Added `--no-input` global flag

docs: improved readme

---

src/commands/whoami.ts
src/services/affinidi/auth/index.ts
src/services/affinidi/auth/token.ts
src/services/affinidi/errors/index.ts

Added principal key in OauthCred.json

fix:  principal id data structure

---

README.md
src/commands/generate/app.ts
src/common/constants.ts
src/helpers/app.ts
src/services/generator/auth0.ts

Change affinidi generate app structure to accomadate provider-framework-library structure.
Add support for django reference apps for auth0 and affinidi providers.
Close FTL-12402, FTL-12457

feat: change affinidi generate app structure

---

src/commands/generate/app.ts
src/common/constants.ts
src/helpers/app.ts

feat: (FTL-12541) add implementation to automate the framework, library and redirect uris fetch

---

package-lock.json
package.json
src/services/affinidi/bff-service.ts
src/services/affinidi/errors.ts

<details><summary>Click to show screenshot</summary>
</details>
NOTE: currently `minimumSupportedCliVersion` in BFF is set to `^2.0.0` (v3 was used to show the error)

feat: FTL-12462 force update CLI

---

package-lock.json
package.json
src/common/constants.ts
src/services/affinidi/bff-service.ts
src/services/affinidi/bff-service.types.ts
src/services/affinidi/vp-adapter/index.ts

<details><summary>Click to show screenshots</summary>
Show errors on project/login config resource creation when limit reached
Fix bug on select-project command
</details>
NOTE: 
- show errors on project/login config resource creation when limit reached
- fix bug on select-project command

feat: FTL-12673 resource limit error handling on CLI

---

CONTRIBUTING.md
README.md
src/commands/whoami.ts

Updates:
- Updated Session and configuration files section based on the latest version.
- Updated `whoami` command description based on the latest version.
- Updated CONTRIBUTING.md removing integration tests

docs: minor updates on readme file

---

src/services/affinidi/bff-service.ts
src/services/affinidi/errors.ts

<details><summary>Click to show before and after changes screenshots</summary>
</details>

fix: show proper auth error for all commands

---

README.md
src/commands/generate/app.ts
src/helpers/app.ts

Also, fix bug related to all frameworks being displayed for one provider in reference app generation
Closes AFFBK-386

feat: add support for multiple libraries for reference apps

---

src/commands/generate/app.ts
src/helpers/app.ts

feat: create a new login config if it doesn't exist for the reference apps

---

src/commands/login/create-config.ts
src/commands/login/update-config.ts
src/common/validators.ts
test/helpers/validator.test.ts

fix: (FTL-13766) gracefully handle extra spaces for redirect-uris input

---

README.md
scripts/vp.yaml
src/commands/login/list-users-in-group.ts
src/common/validators.ts
src/services/affinidi/vp-adapter/index.ts
src/services/affinidi/vp-adapter/vp-adapter.api.ts
test/commands/login/users-of-groups.test.ts

These recordings are before sorting was implemented:
https://github.com/affinidi/affinidi-cli/assets/112941926/eb7b6989-077d-4b49-b72b-eb4ad022ea01
https://github.com/affinidi/affinidi-cli/assets/112941926/e31fba6d-42b4-445c-8cf5-b5072cdccdb7

feat(FTL-13450): add pagination to list-users-in-group command

---

docs/generate.md
src/commands/generate/app.ts

Updates:
- Change the wording from reference app to sample app for the generate app command.

docs(AIVD-108): Updated wording on generate app

---

docs/token.md
package-lock.json
package.json
src/commands/token/create-token.ts
test/commands/token/token.test.ts

Ready-to-use PAT can be created with `--with-permissions` flag for `token create-token` command.

feat: FTL-14135 create ready-to-use PAT with quiet flag

---

README.md
docs/generate.md
docs/iam.md
docs/iota.md
docs/issuance.md
docs/login.md
docs/project.md
docs/start.md
docs/stop.md
docs/token.md
docs/wallet.md
docs/whoami.md

- Generated readme for the Issuance command.

docs: generated readme to manage issuance

---

.github/workflows/checks.yml

adds missing library actions runner

fix: add libsecret-dev
